import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navber from "@/app/Components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['400', '600', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="white">
      <body
        className={`${roboto.className} antialiased bg-white text-black`}
      >
        <Navber />
        {children}
      </body>
    </html>
  );
}
